server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.indianfuturebillionaire: DEBUG


aggregator:
  ring-buffer-size: 65536
  defaultTimeframe: "1m"
  enablePartialBars: true
  partialBarThresholdPercent: 0.02
  quietZoneThresholdMinutes: 5
  multiTimeframes: [ "1m", "5m" ]
  subCycle: true
  barMergeThresholdVolume: 100
  barLockExtreme: false
  barSoftCloseSeconds: 30
  barFinalizeGraceSeconds: 10

risk:
  meltdown-threshold: 50000
  meltdown-ring-buffer-usage-threshold: 0.90
  daily-limit: 1000

indexes:
  preload: ["NIFTY50", "NIFTY100", "NIFTY500", "NIFTYMIDCAP100", "NIFTYSMALLCAP100"]

aws:
  region: "ap-south-1"

hpc:
  meltdownSidecar:
    spikeThresholdRate: 20000
    minimumActiveMillis: 5000


